#image:
#  - Ubuntu1804
#  - Visual Studio 2017
#  
#dotnet_csproj:
#  patch: true
#  file: '**\*.csproj'
#  version: '{version}'
#  package_version: '{version}'
#  assembly_version: '{version}'
#  file_version: '{version}'
#  informational_version: '{version}'
#  package_release_notes: '$(APPVEYOR_PULL_REQUEST_TITLE) - $(APPVEYOR_REPO_BRANCH)'

# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master
  version: 1.0.{build}
  configuration: Release
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  

# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
  branches:
    only:
      - /feature/.*
  version: 1.0.{build}-pre
  configuration: Debug
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug

#version: 1.0.{build}

#build:
#  publish_nuget: true
#  publish_nuget_symbols: true
#  include_nuget_references: true
#  verbosity: minimal


#  
#before_build:
#  - ps: dotnet restore
#    
#after_build:
#  - ps: >- 
#        if ($env:APPVEYOR_REPO_TAG -eq "true") {
#          dotnet pack .\DataflowPipelineBuilder -o ..\Artifacts
#        } 
#        else {
#          dotnet pack .\DataflowPipelineBuilder -o ..\Artifacts --version-suffix "pre"
#        }
#
##artifacts:
##  - path: Artifacts\*
#    
#deploy_script:
#  - ps: appveyor PushArtifact Artifacts\*.nupkg
#    

# settings are the same for  both Nuget providers, except "on:" condition
#deploy:
#  - provider: NuGet
#    on:
#      branch: master
#      
#  - provider: NuGet
#    on:
#      appveyor_repo_tag: true